name: Test and Build

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.11]

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}

        -   name: Install dependencies
            run: |
                make install-ci

        -   name: Run pytest
            run: |
                pytest --cov=src --cov-report=xml --cov-report=term-missing

        ## GHCR is not available for private repo
        ## https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
        # -   name: Log in to GHCR
        #     uses: docker/login-action@v2
        #     with:
        #         registry: ghcr.io
        #         username: ${{ github.actor }}
        #         password: ${{ secrets.GITHUB_TOKEN }}

        # -   name: Build Docker image
        #     run: |
        #         python serve/build_context.py
        #         docker build -f serve/Dockerfile -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

        # -   name: Push Docker image to GHCR
        #     run: |
        #         docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
